data = "UEsDBBQAAAAIABWQbE31hZpVIQAAACUAAAAKAAAAc2VjcmV0LnR4dPPMK05NzilNqq7MLy0tjS9OTY3PTUxMBFKpIDozBwhqAVBLAQIfABQAAAAIABWQbE31hZpVIQAAACUAAAAKACQAAAAAAAAAIAAAAAAAAABzZWNyZXQudHh0CgAgAAAAAAABABgAFERr9HZ61AFRZtDodnrUAVFm0Oh2etQBUEsFBgAAAAABAAEAXAAAAEkAAAAAAA==".decode('base64')

file = open('rafli', 'w')
file.write(data)
file.close()
